// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFxaEpJAk5uZ5tuBJnsBf5CrbP-VkQT9o',
    appId: '1:666954474736:ios:b7403f28fccddf19c44e35',
    messagingSenderId: '666954474736',
    projectId: 'nayadokan-d6874',
    storageBucket: 'nayadokan-d6874.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFxaEpJAk5uZ5tuBJnsBf5CrbP-VkQT9o',
    appId: '1:666954474736:ios:b7403f28fccddf19c44e35',
    messagingSenderId: '666954474736',
    projectId: 'nayadokan-d6874',
    storageBucket: 'nayadokan-d6874.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA62VXMo0VCsVGuo6woVJLsJgX6wI5ZEcY',
    appId: '1:666954474736:web:b5db9004a736134ec44e35',
    messagingSenderId: '666954474736',
    projectId: 'nayadokan-d6874',
    authDomain: 'nayadokan-d6874.firebaseapp.com',
    storageBucket: 'nayadokan-d6874.firebasestorage.app',
    measurementId: 'G-Q5JE67L8SE',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA62VXMo0VCsVGuo6woVJLsJgX6wI5ZEcY',
    appId: '1:666954474736:web:b5db9004a736134ec44e35',
    messagingSenderId: '666954474736',
    projectId: 'nayadokan-d6874',
    authDomain: 'nayadokan-d6874.firebaseapp.com',
    storageBucket: 'nayadokan-d6874.firebasestorage.app',
    measurementId: 'G-Q5JE67L8SE',
  );

}